spring:
  cloud:
    azure:
      # Properties like spring.cloud.azure.credential.client-id are global properties.
      # Properties like spring.cloud.azure.active-directory.credential.client-id are Microsoft Entra ID properties.
      # If Microsoft Entra ID properties is not configured, global properties will be used.
      #      credential:
      #        client-id:
      #        client-secret:
      #      profile:
      #        tenant-id:
      active-directory:
        b2c:
          enabled: true
          base-uri: https://kannanb2c.b2clogin.com/kannanb2c.onmicrosoft.com/
          credential:
            client-id: ${AD_CLIENT_ID} # update client id
            client-secret: ${AD_CLIENT_SECRET} # update client secret
          login-flow: sign-up-or-sign-in # default to sign-up-or-sign-in, will look up the user-flows map with provided key.
          logout-success-url: http://localhost:8080/login
          user-flows:
            password-reset: B2C_1_sampleSbApp_password-reset
            profile-edit: B2C_1_sampleSbApp_profile-editting
            sign-up-or-sign-in: B2C_1_sampleSbApp
#          user-name-attribute-name: ${USER_NAME_CLAIM}
####################################################################################
